### ISSUE TITLE
Some funcs hard to use compatibly on stdweb & native

### ISSUE THREAD

**Issue by esrauch** [grovesNL/glow#104]
For example, storing a location and reusing it works with native but not with stdweb, e.g. this will compile on native but not on stdweb:

let loc = gl.get_uniform_location(program, "some_uniform");
gl.uniform_1_i32(loc, 1);
 [...later...]
gl.uniform_1_i32(loc, 2);

The weirdness is that on web \<Context as HasContext\>::UniformLocation is non-Copy: on native it is just a u32. The webgl uniform1f() semantics seem like more of a borrow of the WebGLUniformLocation rather than a move so the equivalent JS would also just work.

In reality this is maybe not the end of the world, you can support both platforms if you explicitly .clone() at all call sites that have these maybe-Copy types as parameters and it will compile cross-platform, it's just kind of weird.

**Comment by grovesNL** [comment]
Thanks for reporting the issue! Does this problem still exist on `master`? Uniform locations should be passed by reference now since https://github.com/grovesNL/glow/commit/45d4c1b6c38d3fdb7125d3425fba9c5bc437b014

It's been a while since we made a release, so we could make a release soon if this is fixed for you on `master`.

**Comment by esrauch** [comment]
Yep, on master `uniform_1_i32(Some(&loc), 0)` works on both. I'm fine using master until the next release, thanks!
