### ISSUE TITLE
Allow more buffer data types

### ISSUE THREAD

**Issue by gennyble** [grovesNL/glow#164]
Currently, as far as I can tell, there is only `Cotext::bind_buffer_u8_slice`. I've been putting floats in my Buffers by doing a mem::transmute, which probably isn't the best idea.

The implementation for `bind_buffer_u8_slice` (seen [here](https://github.com/grovesNL/glow/blob/5bafcb855595c00aaa2c440c32578b060a139556/src/native.rs#L461-L469)) has to cast the slice to a `*const c_void` anyway. Can we offer functions for other data types, or possibly even make it a generic? I'm not sure a generic is a good idea, but it might work? 

I know I'd love to see a `bind_buffer_f32_slice` or similar. I'd be happy to open a PR if it's something you're interested in.

**Comment by grovesNL** [comment]
Hi @gennyble! We could definitely consider exposing more functions here, but maybe we could recommend some ways to cast data to `&[u8]` instead?

The reason we only expose byte/`u8` slices there today is because GL has some restrictions about padding or alignment depending on how the data is used. Because of those restrictions, it's a bit easier to let the crate using glow decide how to reinterpret their data into bytes instead of supporting some limited cases (like `&[f32]`).

For example, the simple case of `&[f32]` to `&[u8]` could be handled by something like [`bytemuck`](https://docs.rs/bytemuck/1.6.1/bytemuck/fn.bytes_of.html). It can handle more complicated cases too, like casting structs that contain both `f32` and `i32` to `&[u8]`. There are also some crates that are for use with GL layouts, like [`std140`](https://docs.rs/std140/0.2.4/std140/).

**Comment by cielabo** [comment]
Hi there! 
Thank you @grovesNL for recommending `bytemuck`! It works very well for me in most cases. However, I have a problem where I want a buffer to contain a `vec3` array, but the input data type (`[[f32; 4]]`) doesn't work with `bytemuck`'s `Pod` trait. I also can't really put it in a `std140` array as those have a constant size known at compile time. Does anyone know how I can still somehow get this data into my buffer? Thanks!

**Comment by grovesNL** [comment]
@cielabo where is `&[[f32; 4]]` used? Maybe you're looking for something like [`try_cast_slice`](https://docs.rs/bytemuck/1.7.0/bytemuck/fn.try_cast_slice.html)?

**Comment by cielabo** [comment]
Yeah, that's exactly what I needed, thank you so much! ^^

**Comment by grovesNL** [comment]
Closing because I think this was answered – feel free to reopen if not!
