### ISSUE TITLE
about missed glBegin

### ISSUE THREAD

**Issue by oldoldman** [grovesNL/glow#199]
I can't find ```glBegin``` in ```GlFns``` , is this by design? I would like it for completeness. Many thanks.

**Comment by grovesNL** [comment]
Hi @oldoldman! :wave: We don't currently support the older fixed rendering pipeline because the portability isn't very good and it's generally considered legacy functionality at this point. For example, it's deprecated by the OpenGL Core profile and not supported by WebGL 1+/OpenGL ES 2+. If possible I'd recommend using the programmable rendering pipeline instead.

**Comment by oldoldman** [comment]
thank you. got it.
