### ISSUE TITLE
Drawing a full-window fragment shader

### ISSUE THREAD

**Issue by joseksilva** [grovesNL/glow#58]
Sorry if it's a noob question, I'm new into graphics programming and I didn't find how to do what I want in the documentation...

I created a fragment shader which works exactly as I need when I open it on programs like glslViewer so now I need to display it in my application. 

I'm trying to do so with glow but I'm stuck in the vertex shader's triangle of the example project. No matter what I do, all fragment shaders that I try works only inside this triangle and I can't change him.

So I'm seeking some advince to get rid of this vertex shader and use only use my fragment shader, like I do in glslViewer. Or at least use a vertex shader that covers all screen.

Another question is how can I get some data (like textures and positions) from my rust code into my fragment shader code. glslViewer has some special variable names for that like u_tex0, u_tex1, u_resolution, u_time... but it seems to not works for glow.

**Comment by grovesNL** [comment]
You'll need both a vertex shader and fragment shader for this, but you can have a vertex shader just create a [single full screen quad (two triangles)](https://stackoverflow.com/questions/2588875/whats-the-best-way-to-draw-a-fullscreen-quad-in-opengl-3-2) or a [triangle that covers the full screen](https://rauwendaal.net/2014/06/14/rendering-a-screen-covering-triangle-in-opengl/).

For uniforms like `u_resolution`, you'd use [any of the functions prefixed with `uniform_`](https://github.com/grovesNL/glow/blob/54a4df6e7d7ae4c435397c1a7f5bbdb565206078/src/lib.rs#L451) to set data for the uniform. These uniforms need to be declared in the fragment shader and be used somewhere in the shader (otherwise they'll be automatically removed from the shader).

If you're interested, the [#games-and-graphics channel on the unofficial Rust Community Discord](https://bit.ly/rust-community) might be a helpful resource to get started with Rust and GL.

**Comment by joseksilva** [comment]
Thank you @grovesNL! 

Your tips worked like a charm.
